
find_package(CUDA_wrap REQUIRED)
list(APPEND ALL_INCLUDE_DIRECTORIES ${CUDA_INCLUDE_DIRS})
list(APPEND ALL_LIBRARIES -lcudart -lcuda)
get_filename_component(CUDA_LIB_DIR "${CUDA_CUDART_LIBRARY}" PATH)
list(APPEND ALL_LIBRARY_DIRS ${CUDA_LIB_DIR})
